language: node_js
node_js:
  - 8
  - 9
  - 10
  - 11
cache:
  directories:
    - node_modules
    - client/node_modules
script:
  - cd client
  - npm install --ignore-scripts
  - npm test
  - cd ..
  - npm install
  - npm test
env:
  global:
    - SKIP_PREFLIGHT_CHECK=true
    - NODE_ENV=test
